### ISSUE TITLE
Issues not displayed for third party repos (I think?)

### ISSUE THREAD

**Issue by stilez** [pockethub/PocketHub#852] opened 2015-07-29 00:49 UTC
Sorry if I have misinterpreted anything. 

In the app, when I visit my own repo, I can click on an item in "news" and it'll show me the commit, the comment etc as I'd expect.

If I submit a PR to someone else's repo where I don't have write/commit access, or want to view commits to someone else's repo, then I get a blank page. Logcat seems to hint that there's some kind of error/permissions issue behind this problem, but it's very unclear - I can't even be sure if it's android or github API that's faulting.

In any event I'm not seeing an "issues" tab visible, as the screenshots seem to suggest.

As one of my main uses for the app is to track my PRs, the difficulty in listing them and inability to see latest comments on them is a real problem.

**Comment by Meisolsson** [comment] 2015-07-29 06:15
You should still have the ability to read a repo if it has third-party restrictions. But I guess there could be a issue with getting news from it.

I'll check with GitHub support and look into it myself.

**Comment by fadils** [comment] 2015-07-29 06:25
This is probably dupe of #312

**Closed** 2015-08-03 11:34 UTC
