### ISSUE TITLE
Web page not available

### ISSUE THREAD

**Issue by shvelo** [pockethub/PocketHub#402] opened 2013-09-01 10:38 UTC
Screenshot:  
 <a href='http://i.imgur.com/vGoVP9r' title=''><img src='http://i.imgur.com/vGoVP9r.jpg' alt='' title='Hosted by imgur.com' /></a>

Platform: Android 2.3 (CM7.2)  
Build: F-Droid, 1.7.1  
Device: Motorola Bravo

**Comment by larsgrefer** [comment] 2015-10-10 18:46
I think we should close this, on my phone everything works and the issue is pretty old

**Closed** 2017-06-12 17:44 UTC
