### ISSUE TITLE
422 error

### ISSUE THREAD

**Issue by FreeVicto** [pockethub/PocketHub#897] opened 2015-10-08 05:46 UTC
same account login through webpage is fine(2 step authorization)，but this app withe a error as below:

validation failed(422):oauthaccess resource with'description' field already exits.

**Comment by Meisolsson** [comment] 2015-10-08 15:15
I'm not sure what you're saying, give us the steps to reproduce and a log.

**Comment by Meisolsson** [comment] 2015-11-21 10:05
Since there has been no answer in over a month I'm closing this

**Closed by Meisolsson** 2015-11-21 10:05 UTC
