### ISSUE TITLE
Changing username results in 404 errors

### ISSUE THREAD

**Issue by SamThompson** [pockethub/PocketHub#959] opened 2015-11-25 23:17 UTC
I recently changed my username, and I get 404 errors when I try to load anything.

I haven't looked at the github api, but there should be some endpoint to get the username of a given oauth token.

I would just log out and back in, but I can't seem to find where to log out (not sure if this is related).

**Comment by fadils** [comment] 2015-11-26 02:30
You should build against our latest `master`. Meanwhile, we are trying to update the PlayStore version, as soon as possible.

**Comment by hzsweers** [comment] 2015-11-26 03:10
Sam isn't using the play store version I don't think

**Comment by fadils** [comment] 2015-11-26 03:54
Ah, my bad..
Are you doing similar with #819 ?

**Comment by SamThompson** [comment] 2015-11-26 04:00
Yep, that's it. For some reason that issue didn't come up when I searched earlier. Feel free to mark this as a duplicate

**Comment by hzsweers** [comment] 2015-11-26 04:09
Dupe of #819

**Closed by hzsweers** 2015-11-26 04:09 UTC
